Sniper
ModDota/AbilityLuaSpellLibrary pull request #5
Opened 2017-12-05 14:16 UTC by Wouterz90

I think the implemented way of using abilities with charges is the easiest to maintain, and to implement for new users. Would like to hear your opinions on this.

2017-12-05 18:54 UTC, Perryvw requested changes
Needs some small changes, looks good overall

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/npc/npc_abilities_custom.txt
> +        "ScriptFile"            "heroes/util/base_ability_charges.lua"
this indentation, ocd = triggered

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/npc/npc_abilities_custom.txt
> +#base "heroes/sniper.kv"
keep open line here

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/vscripts/heroes/sniper/assassinate.lua
> +-- The spell is almost completely different with and without Aghanims Scepter. The order is always normal then scepter
Always? Where else?

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/vscripts/heroes/sniper/assassinate.lua
> +    if not self:GetCaster():HasScepter() then
get rid of the not here and swap cases

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/vscripts/heroes/sniper/assassinate.lua
> +    self:GetCaster():RemoveModifierByName("modifier_sniper_assassinate_caster_lua")
Should probably remove by name and caster.

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/vscripts/heroes/sniper/shrapnel.lua
> +        -- Add shrapnel particl effect
typo

2017-12-05 18:54 UTC, Perryvw commented on game/scripts/vscripts/heroes/sniper/shrapnel.lua
> +    }
`ApplyDamage(damageTable)`?

2017-12-05 21:20 UTC, Wouterz90 commented on game/scripts/vscripts/heroes/sniper/shrapnel.lua
> +    }
Not sure why this still shows

2017-12-06 09:21 UTC, Perryvw requested changes
some formatting issues

2017-12-06 09:21 UTC, Perryvw commented on game/scripts/npc/heroes/sniper.kv
> +		"AbilityBehavior"       "DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
indentation

2017-12-06 09:21 UTC, Perryvw commented on game/scripts/npc/heroes/sniper.kv
> +		"AbilityBehavior"       "DOTA_ABILITY_BEHAVIOR_PASSIVE"
indentation

2017-12-06 09:21 UTC, Perryvw commented on game/scripts/npc/heroes/sniper.kv
> +	    "AbilityTextureName"      "sniper_take_aim"
indentation

2017-12-06 09:21 UTC, Perryvw commented on game/scripts/npc/heroes/sniper.kv
> +	    "AbilityTextureName"      "sniper_assassinate"
indentation

2017-12-06 09:21 UTC, Perryvw commented on game/scripts/npc/npc_abilities_custom.txt
> +#base "heroes/sniper.kv"
I meant keep an open line between the #base lines and DOTAAbilities, so move this to line 5 and keep 6 open.

2017-12-06 13:49 UTC, Perryvw approved these changes

2017-12-06 13:49 UTC, merged